### ISSUE TITLE
Default Config file missing line break

### ISSUE THREAD

**Issue by bkelly16** [joshuaboud/cephgeorep#1]
Default config file created is missing line break and will fail to run.
`[root@vfsgw01 cephgeorep]# cephfssyncd 
SND_SYNC_DIR=

RECV_SYNC_HOST=

RECV_SYNC_DIR=

LAST_RCTIME_DIR=/var/lib/ceph/cephfssync/

SYNC_FREQ=10

IGNORE_HIDDEN=false

RCTIME_PROP_DELAY=5000

COMPRESSION=falseLOG_LEVEL=1

terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted
`
Put line break after COMPRESSION and it runs correctly

**Comment by joshuaboud** [comment]
Fixed, good catch thanks
